[tool.poetry]
name = "features_nonlinear"
version = "0.1.0"
description = "Transformaciones no lineales y automáticas"
authors = ["Tu Nombre <email@ejemplo.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26"
pandas = "^2.2"
autofeat = "^2.0"
scikit-learn = "^1.4"
loguru = "^0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
